### DISCUSSION TITLE
MQTT as a controller type

### DISCUSSION THREAD

**Discussion by bkbartk** [awawa-dev/HyperHDR#618] [Q&A] [answered]
Hello,

I'm new to HyperHDR and I was wondering if it is possible to have the led output send to MQTT?

Let me explain,
Right now I have piccap and hyperHDR installed on my LG WebOS TV.

in hyperHDR I have 1 ledcontroller which now sends RGB values to a file (controller type Debub/file)
that part works,

but what I would Like is to send this output not to a file but to MQTT so in my home assistant I can match other lights with the primary color of my tv.
(doesn't need to be MQTT, but I think this makes most sence)

Should this be possible? or am I mistaken about this?

**Comment by awawa-dev** [comment]
Hi
Not exactly MQTT but have you seen recently new method added to JsonAPI to retrieve an average color? Can be used as easily as every GET request so you can use it almost everywhere. More: https://github.com/awawa-dev/HyperHDR/pull/611

**Reply by bkbartk** [reply]
Cool, that one is interesting,
a few remarks, it's not in current release yet, so I might have to wait or learn how to build for webos, so probably waiting is faster.
Also I have to create a polling mechanism with an interval, The original requester want to do this only on media state change where I would like to have this semi real-time, I think 500ms delay would be acceptable. This might cause a huge network load, 

If I could use MQTT directly or maybe just run a command like this when the output changes (I still have to find an mqtt client, this is an example)
`/tmp/mosquitto_pub -h 192.168.0.22 -u mqttuser -P mqttpasswd -m "$BUF" -t HyperHDR/instance0`
a polling mechanism won't be needed anymore which would increase the performance and reduce the load on HyperHDR.

Still as soon as the JsonAPI change is in the release, I will check if this fits my needs.

**Reply by awawa-dev** [reply, marked as answer]
I think for simple color averaging even a real time stream using MQTT subscription is OK. There are a few nuances to consider: how to behave when the LED device is off (currently the color is set to black), what averaging algorithm to use (currently simple averaging, but HyperHDR has long since introduced square root averaging as well), sent colors before smoothing (current behavior for new JSon method or after smoothing processing). Colors are sent over the network also e.g. using udpraw LED driver in simple {r,g,b} format but you must implement some kind of simply UDP listener just like WLED. UDP is a much more preferred way to stream live data than TCP: we can live on if the occasional frame is lost, and in return we have much lighter communication.

**Reply by bkbartk** [reply]
I see udpraw now,
I think that could work and looks a better solution for me then the JsonAPI. I still have to build an UDP Listener. I will give this a try when I have some time.
for the considerations you mentioned, those are all true, but for all other outputs, the same considerations should have been made already. So I would think it makes sense to follow the same line everywhere.
When the device is off, sending black makes sense black is no light, in some scenarios "null" maybe makes more sense. but changing that might breaks current implementations. So I think those dissension should be up to the developers.

**Reply by awawa-dev** [reply]
During the implementation, it was necessary to make certain assumptions that had not been specified before, some of which can be extended or changed in the future with an additional option in the new API. BTW HyperHDR has a built-in UDP receiver, as does WLED (enabled in advanced->network this is mainly used to quickly synchronize HyperHDR instances between different devices). It's c++/qt but the schema should be similar: https://github.com/awawa-dev/HyperHDR/blob/master/sources/utils/RawUdpServer.cpp

**Reply by bkbartk** [reply]
I couldn't get my rawudp listener to work, but I found some solution which did the trick for me, So no MQTT needed and everything works great, than you.

**Reply by Nartsuto** [reply]
@bkbartk - I am trying to do the same thing. Can you clarify what your solution was?

**Comment by bkbartk** [comment]
On home assistant I installed the node-red add-on and integration
in the add-on added an UDP listener
![image](https://github.com/awawa-dev/HyperHDR/assets/17070805/27df494d-840c-4748-96c0-9ed766104a23)
and send this to a sensor
![image](https://github.com/awawa-dev/HyperHDR/assets/17070805/1957ec40-0981-41df-af0e-524fca6c1a97)
expression
`$substringBefore($substringAfter($string(payload), ":["),"]")`
This sensor is then automatically added to the integration. (I don't know how to remove them)

then in HA create an automation like this
```
alias: Ambilight
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.sensor1
    to: null
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.living_room_tv
        state: "off"
      - condition: state
        entity_id: media_player.living_room_tv
        state: unavailable
action:
  - service: light.turn_on
    data:
      rgb_color:
        - "{{ states('sensor.sensor1').split(',')[0] | int }}"
        - "{{ states('sensor.sensor1').split(',')[1] | int }}"
        - "{{ states('sensor.sensor1').split(',')[2] | int }}"
    target:
      entity_id: light.ledstrip_light
mode: single
```

this works perfectly for me.

Only one thing,
sometimes hyperhdr does not automatically start UDPRaw,
at that point it starts working after restarting the TV on after changing the refresh time and save again
![image](https://github.com/awawa-dev/HyperHDR/assets/17070805/5f66174f-9766-4dce-a8e8-0e30d24fca2c)
not sure why.

**Comment by awawa-dev** [comment]
> that point it starts working after restarting the TV on after changing the refresh time and save again not sure why.

The answer should be in the HyperHDR logs. And isn't stopping and restarting the UDPRraw LED device in the remote tab enough?

**Reply by bkbartk** [reply]
I haven't take the time to dive in to this yet because I'm planning to migrate to WLED and at that point it might not be an issue any more.
It was just a comment on if anything would go wrong, not really a question.
but if I find something in the logs I will  check it out.

**Comment by raphaeleduardo42** [comment]
I was using the solution from @bkbartk, but after the release of 20.0.0.0 I came with better solution using the Json API and skipping node-red entirely.

`config.yaml`
```yaml
logbook:
...
  exclude:
    entities:
      - sensor.hyperhdr_average_color
...


rest:
  - resource: http://{ip}:{port}/json-rpc?request=%7B%22command%22:%22current-state%22,%22subcommand%22:%22average-color%22,%22instance%22:1%7D # Link for the Average Color of Instance Index 1
    scan_interval: 1
    sensor:
      - name: HyperHDR Average Color
        unique_id: #Pick one at https://www.uuidgenerator.net/
        force_update: true
        json_attributes_path: "$.info"
        json_attributes:
          - "red"
          - "blue"
          - "green"
        icon: mid-palette-swatch
```

```
alias: Ambilight
description: Change lights to HyperHDR average color using REST Api f rom V2024.0.0.0 # https://github.com/awawa-dev/HyperHDR/discussions/618
trigger:
- platform: state
  entity_id:
  - sensor.hyperhdr_average_color
condition:  # Update to your needs
- condition: state
  entity_id: light.hyperhdr
  state: 'on'
action:
- service: light.turn_on
  data:
    rgb_color:
    - '{{ state_attr(''sensor.hyperhdr_average_color'', ''red'') }}'
    - '{{ state_attr(''sensor.hyperhdr_average_color'', ''green'') }}'
    - '{{ state_attr(''sensor.hyperhdr_average_color'', ''blue'') }}'
  target:
    entity_id:
    - light.{target} # Update to your needs 
mode: single
```
