### DISCUSSION TITLE
Nvidia Shield LUT Calibration

### DISCUSSION THREAD

**Discussion by jhomeassistant** [awawa-dev/HyperHDR#951] [Q&A]
I'm using the F3 firmware on my MS2130. 

I can't seem to get accurate color reproduction with an SK6812 cold white LED strip when using a Nvidia Shield as the source. I've tried downloading the provided MS2130 LUT table and calibrating my own LUT table both with an HDR windows PC as well as using an SDR browser on my Shield.

In all three cases I have to lower the green and blue temperature to around 160-180 from 255, and the red to around 220 from 255 for somewhat accurate color reproduction. These are just rough ranges and could be better calibrated.

Are there any known issues when using a Nvidia Shield or could I be missing something?

Thanks!

**Comment by awawa-dev** [comment]
Hi
Which depth of color you are using on Windows (ex. 10 or more bits RGB)? Did you disable all Windows features (mainly Windows 11) that can affect calibration like night colors, auto-hdr, automatic manage color for apps, graphic driver options for colors on default etc ) You can test new calibration feature, completely rewritten:
https://github.com/awawa-dev/HyperHDR/pull/896

This is my results using Windows 11, ms2130 (F3, 1080p yuv) and Firefox browser with new LUT calibration:
```
Calibrated:
       White: [255 255 255] => [255 255 255] [corrected]
         Red: [255   0   0] => [251   0   0] [corrected]
       Green: [  0 255   0] => [  0 255   0] [corrected]
        Blue: [  0   0 255] => [  0   0 255] { [  0   0 251] } [corrected, source noice detected]
    UpperRed: [192   0   0] => [185   0   0] { [189   0   0] [181   0   0] } [corrected, source noice detected]
  UpperGreen: [  0 192   0] => [ 26 195   0] { [ 23 191   0] [  0 202   0] [ 28 199   0] } [corrected, source noice detected]
   UpperBlue: [  0   0 192] => [  0   0 192] [corrected]
   MiddleRed: [128   0   0] => [124   0   0] { [127   0   0] [129   0   0] [121   0   0] } [corrected, source noice detected]
 MiddleGreen: [  0 128   0] => [  0 131   0] [corrected]
  MiddleBlue: [  0   0 128] => [  0   0 127] { [  0   0 130] [  0   0 124] } [corrected, source noice detected]
      LowRed: [ 64   0   0] => [ 62   0   0] [corrected]
    LowGreen: [  0  64   0] => [  0  67   0] [corrected]
     LowBlue: [  0   0  64] => [  0   0  61] [corrected]
      Yellow: [255 255   0] => [244 255   0] [corrected]
     Magenta: [255   0 255] => [247   0 253] { [252   0 255] [242   0 248] } [corrected, source noice detected]
        Cyan: [  0 255 255] => [  0 255 241] { [ 41 255 242] [  0 255 251] } [corrected, source noice detected]
      Orange: [255 128   0] => [247 133   0] [corrected]
    LimeBlue: [  0 255 128] => [ 25 255 124] [corrected]
        Pink: [255   0 128] => [250   0 125] { [255   0 125] } [corrected, source noice detected]
     LimeRed: [128 255   0] => [133 255   0] [corrected]
       Azure: [  0 128 255] => [  0 132 252] [corrected]
      Violet: [128   0 255] => [121   0 254] [corrected]
     WHITE_0: [  0   0   0] => [  0   0   0] [corrected]
     WHITE_1: [ 16  16  16] => [ 17  17  17] [corrected]
     WHITE_2: [ 32  32  32] => [ 33  33  33] [corrected]
     WHITE_3: [ 48  48  48] => [ 49  49  49] [corrected]
     WHITE_4: [ 64  64  64] => [ 65  65  65] { [ 67  67  67] [ 63  63  63] } [corrected, source noice detected]
     WHITE_5: [ 80  80  80] => [ 81  81  81] { [ 83  83  83] [ 79  79  79] } [corrected, source noice detected]
     WHITE_6: [ 96  96  96] => [ 99  99  99] [corrected]
     WHITE_7: [112 112 112] => [114 114 114] [corrected]
     WHITE_8: [128 128 128] => [131 131 131] [corrected]
     WHITE_9: [144 144 144] => [146 146 146] { [149 149 149] [143 143 143] } [corrected, source noice detected]
    WHITE_10: [160 160 160] => [162 162 162] { [166 166 166] [159 159 159] } [corrected, source noice detected]
    WHITE_11: [176 176 176] => [180 180 180] [corrected]
    WHITE_12: [192 192 192] => [196 196 196] { [200 200 200] [192 192 192] } [corrected, source noice detected]
    WHITE_13: [208 208 208] => [212 212 212] { [216 216 216] [208 208 208] } [corrected, source noice detected]
    WHITE_14: [224 224 224] => [230 230 230] [corrected]
    WHITE_15: [240 240 240] => [248 248 248] [corrected]
    WHITE_16: [255 255 255] => [255 255 255] [corrected]
```
