### ISSUE TITLE
Home assistant hyperion integration is broken

### ISSUE THREAD

**Issue by nurikk** [awawa-dev/HyperHDR#118]
Hi, I can't add hyperhdr to home assistant using default integration.

## Bug report, debug log and your config file (FULL LOGS ARE MANDATORY)
HyperHDR logs:

```
2021-09-09T15:28:24.830Z [JSONCLIENTCONNECTION] (JsonAPI.cpp:89) Client '::ffff:192.168.1.200' switch to HyperHDR instance 0
2021-09-09T15:28:24.835Z [JSONSERVER] (JsonServer.cpp:105) New connection from: ::ffff:192.168.1.130 
2021-09-09T15:28:24.837Z [JSONCLIENTCONNECTION] (JsonAPI.cpp:89) Client '::ffff:192.168.1.200' switch to HyperHDR instance 0
2021-09-09T15:28:24.970Z [JSONSERVER] (JsonServer.cpp:121) Connection closed
2021-09-09T15:28:24.976Z [JSONSERVER] (JsonServer.cpp:121) Connection closed
```
Home assistent logs are empty, ui shows me this message
<img width="407" alt="Screenshot 2021-09-09 at 11 34 27 PM" src="https://user-images.githubusercontent.com/1525421/132717030-1e1a2d7c-e7fa-4035-be5e-bb1a7ad37921.png">

#### Steps to reproduce

1. Navigate to homeassistant -> Configuration -> Integrations -> Add integration
2. Search `hyperion`
3. Enter hyperion
4. Select hyperion
5. Enter ip addess
6. Click ok

#### What is expected?
Add hyperhdr integration

#### What is actually happening?
Nothing, only error message

#### System
```
HyperHDR Server: 
- Build:           (HEAD detached at 4e4031c) (Awawa-eba222b/4e4031c-1630846534)
- Build time:      Sep  5 2021 13:29:15
- Git Remote:      https://github.com/awawa-dev/HyperHDR
- Version:         17.0.0.0beta2
- UI Lang:         auto (BrowserLang: en-GB)
- UI Access:       default
- Avail Capt:      Linux (V4L2)
- Database:        read/write

HyperHDR Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.1
- CPU Revision:   c03111
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.17-v7l+ (WS: 32))
- Qt Version:     5.11.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
 ```

Home assistant

## System Health

version | core-2021.9.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 4.9.241-77
arch | aarch64
timezone | Asia/Singapore

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4797
Installed Version | 1.15.2
Stage | running
Available Repositories | 881
Installed Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 18.04.5 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 29.1 GB
disk_used | 8.7 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.12.4), ESPHome (2021.8.2), FTP (4.2.1), File editor (5.3.3), Git pull (7.12.2), Glances (0.13.0), Log Viewer (0.11.1), Mosquitto broker (6.0.1), NGINX Home Assistant SSL proxy (3.0.1), Node-RED (10.0.0), Portainer (2.0.0), SSH & Web Terminal (9.0.1), WireGuard (0.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 5
views | 3
mode | yaml

</details>

**Comment by awawa-dev** [comment]
SSDP was reworked in v17 and may lead to incompatibility with Hyperion plugins.
Log from Home Assistant is misguiding: says it can't no find ATTR_UPNP_SERIAL = "serialNumber" (probably this: [link](https://github.com/home-assistant/core/blob/348d7a5622e8d3f71adbb6272d6ad7442fc6f92e/homeassistant/components/hyperion/config_flow.py#L208) 'no_id') , but if you type your HyperHDR SSDP config address it should be present http://HYPERHDR_IP:PORT/description.xml  
Unless there is some workaround without returning back to old stuff in HyperHDR then maybe it could be 'fixed'. Other proper way is to create a plugin for HyperHDR as some other things in its JSON api also has changed.
Hope you understand then since this is an external application using a plugin created for Hyperion NG, can't consider it as a bug in HyperHDR.

**Comment by nurikk** [comment]
Oh, that's sad that we've lost api compatibility with existing HA integration. HA integration requires freaking hell of copy-paste work. Anyway, thanks for your great work!

**Comment by thehijacker** [comment]
Hello.

Home Assistant integration was working fine with 16.x release but not it is completely broken. I had automation that turned on LED device and USB capture when my TV went on, but this is not working now. Can I use some sort of API call (http rest?) to enable/disable this?

Thank you.

**Comment by awawa-dev** [comment]
Hi
It's not broken but no longer compatible with Hyperion NG plugin. Still you can use HyperHDR's JSON API (now it is even extended with new features compared to Hyperion one) to send commands. For most of them you can use new JSON wizard ('advanced' tab) to create them for you: probably [link](https://postimg.cc/XGF7vpPg) 'All instances (Global)' could work here.

**Comment by thehijacker** [comment]
Managed to implement this json_rpc using HA rest call. FYI:

```
rest_commands:
  hyperhdr_usb_capture:
    url: http://192.168.28.64:8090/json-rpc
    method: POST
    headers:
      accept: 'application/json, text/html'
      user-agent: 'Mozilla/5.0 {{ useragent }}'
    payload: '{	"command":"componentstate", "componentstate": { "component":"VIDEOGRABBER", "state": {{ state }} } }'
    content_type:  'application/json; charset=utf-8'
  hyperhdr_led_device:
    url: http://192.168.28.64:8090/json-rpc
    method: POST
    headers:
      accept: 'application/json, text/html'
      user-agent: 'Mozilla/5.0 {{ useragent }}'
    payload: '{	"command":"componentstate", "componentstate": { "component":"LEDDEVICE", "state": {{ state }} } }'
    content_type:  'application/json; charset=utf-8'
```

And then in my automation:

```
automation:
  - alias: 'TV power over 60W turn on Ambilight'
    id: 'tv_power_over_60W_turn_on_ambilight'
    trigger:
      - platform: template
        value_template: >-
          {{ states('sensor.blitz_socket_sony_energy_power') | int > 60 and is_state('media_player.chromecast_audio', 'off') }}
    action:
      # Prižgi USB capture
      - service: rest_command.hyperhdr_usb_capture
        data: {state: "true"}
      # Prižgi LED okrog TV
      - service: rest_command.hyperhdr_led_device
        data: {state: "true"}
```

Now to test how is CPU usage on my RPi Zero W. It was just under 100% when USB grabber was on. I think I need better Raspberry Pi for running HyperHDR.
