### ISSUE TITLE
18 Beta 3 dashboard doesn't work via internet

### ISSUE THREAD

**Issue by marcosvrs** [awawa-dev/HyperHDR#292]
#### Steps to reproduce
Connect to the HyperHDR dashboard via internet (Tunnel + Traefik)

#### What is expected?
The dashboard to work.

#### What is actually happening?
The HTML is outputted but not rendered.

![Screenshot 2022-07-03 at 15-09-25 https __hyperion marcosvr com](https://user-images.githubusercontent.com/10147574/177041372-62a799b6-f5e5-41fd-a58e-5f87db204d9d.png)

#### System

Running version 18 Beta 3 on a docker. Connecting via Cloudflared Tunnel -> Traefik -> HyperHDR.

**Comment by marcosvrs** [comment]
BTW, it works on v17.

**Comment by awawa-dev** [comment]
> BTW, it works on v17.

On the EXACTLY same container? You must debug it on your own using browser debug console to see network communication (if the contented of the index page is recognized as HTML) and compare it to v17. As saw similar effect and in that case was cause by the OS: dont know if the same happen here.

**Comment by marcosvrs** [comment]
.Dockerfile:
```
FROM debian:stable-slim

ARG release

RUN apt update && \
    apt install --no-install-recommends -yq \
    curl \
    ca-certificates \
    libglib2.0-0 \
    libxcb1 \
    sqlite3 \
    xz-utils && \
    apt -y --purge autoremove && \
    apt clean autoclean && \
    rm -rf /var/lib/{apt,dpkg,cache,log} /tmp/* /var/tmp/* /var/lib/apt/lists/*

RUN curl -fsSL ${release} -o /tmp/HyperHDR.deb && dpkg -i /tmp/HyperHDR.deb

EXPOSE 8090 19444 19445
VOLUME /config

CMD hyperhdr -u /config
```

docker-compose:
```
hyperhdr:
    build:
      context: ./.docker/hyperhdr
      args:
        release: https://github.com/awawa-dev/HyperHDR/releases/download/v18.0.0.0beta3/HyperHDR-18.0.0.0beta3-Linux-x86_64.deb
    container_name: hyperhdr
    ports:
      - 8090:8090
      - 19444:19444
    volumes:
      - ./.docker/hyperhdr/config:/config
    environment:
      TZ: Europe/Berlin
    devices:
      - /dev/input/event5
      - /dev/snd/controlC1
      - /dev/esp8266:/dev/ttyUSB0
      - /dev/video0
      - /dev/video1
    labels:
      com.centurylinklabs.watchtower.enable: false
      traefik.enable: true
      traefik.http.routers.hyperion.rule: Host(`hyperion.example.com`)
      traefik.http.services.hyperion.loadbalancer.server.port: 8090
    restart: unless-stopped
```

At the end, the only thing I change for the version is the `release` argument.

v18 Beta3:
![image](https://user-images.githubusercontent.com/10147574/177042880-3c05c058-bf32-46c3-bb4c-4b9664a7d115.png)

Will send you v17 later.
